### ISSUE TITLE
Any plans to support wxPython Phoenix (3.0+)?

### ISSUE THREAD

**Issue by dougthor42** [newville/wxmplot#16]
Are there any plans to support wxPython Phoenix (3.0+) and Python 3.4+?

**Comment by newville** [comment]
@dougthor42  I'm eager to be able to use matplotlib with wxPhoenix and Python 3.4.   My understanding of the progress on Phoenix may be incomplete,  but a wxPhoenix backend for matplotlib seems to be the main thing keeping me from transitioning many projects (I use wxmplot a lot!) to Python 3.  

As far as I can tell, a Phoenix backend was in progress, but I have to admit that I haven't tried it in many months.   Perhaps you have more information or experience with recent developments?  

So, I think the short answer is "not immediate plans, but I am hopeful that this will be possible soon!".

**Comment by dougthor42** [comment]
Well it's true that wxPython Phoenix on Python3 is still in development. I would consider it in a useable state though - I'm using it for a couple of projects myself.

Sadly I do not have any info on the wxPhoenix backend for MPL. That said, I managed to get your wxmplot working on wxPhoenix + Python 3.4 with a few minor modifications (and absolutely no testing :-P) and some deprecation warnings from MPL.

I'll create a PR and push the code changes so that you can take a look.

Keep in mind that I was only trying to get things working for a simple scatterplot, so there will definitely be more to do.

### Deprecation Warnings:
```
C:\WinPython34_x64\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\backend_wx.py:739: wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`Bitmap` instead
  self.bitmap =wx.EmptyBitmap(w, h)
C:\WinPython34_x64\python-3.4.3.amd64\lib\site-packages\wxmplot\plotpanel.py:488: wxPyDeprecationWarning: Using deprecated class. Use Cursor instead.
  self.canvas.SetCursor(wx.StockCursor(wx.CURSOR_CROSS))
C:\WinPython34_x64\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\backend_wx.py:1039: wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`Bitmap` instead
  self.bitmap =wx.EmptyBitmap(self._width, self._height)
C:\WinPython34_x64\python-3.4.3.amd64\lib\site-packages\matplotlib\backends\backend_wxagg.py:157: wxPyDeprecationWarning: Call to deprecated item BitmapFromBufferRGBA. Use :meth:`Bitmap.FromBufferRGBA` instead.
  agg.buffer_rgba())
```

**Comment by newville** [comment]
@dougthor42 -- that sounds like real progress, and I look forward to a PR!    I'm sure there will be several minor-ish issues, but that some interface-compatibility code could help  --- maybe such a thing exists somewhere in the Phoenix code already.

My understanding is that a Phoenix backend for MPL is expected for 1.5.

**Comment by newville** [comment]
@dougthor42 some progress:  With the current daily builds for wxPython Phoenix 3.0.3 , and matplotlib 1.5.1 I've successfully used wxmplot with both Python 2.7.11 and 3.5.1 (both from Anaconda, and tested so far only on Mac OS X).    

Of course, each of Phoenix-instead-of-Classic and Python3 required a few changes, and may need a bit more work, but it's very encouraging that this is starting to work.

**Comment by newville** [comment]
Phoenix is now supported.
