### ISSUE TITLE
Resize of a PlotPanel

### ISSUE THREAD

**Issue by kuch3n** [newville/wxmplot#23]
Hi, is it possible to resize a PlotPanel?

**Comment by newville** [comment]
@kuch3n  Yes,  I do this all the time.

**Comment by kuch3n** [comment]
How do you achieve this? I cant find any resize function :/

**Comment by newville** [comment]
@kuch3n Umm, since you gave no information about what you have tried, I'll assume you haven't tried anything.   Perhaps wxWindow.SetSize() is all you're looking for?  That's a general wxPython question. 

Closing -- not a issue.
