### ISSUE TITLE
Two plots with different scale

### ISSUE THREAD

**Issue by kuch3n** [newville/wxmplot#24]
Is it possible to plot data like temperature (-25, 40) vs power(0W, 10kW) like this [http://matplotlib.org/examples/api/two_scales.html](url)

**Comment by newville** [comment]
@kuch3n  Yes.  Use `side='right'` to use the right-hand y axis.  See  https://github.com/newville/wxmplot/blob/master/examples/leftright.py

**Comment by kuch3n** [comment]
Nice, thx :+1: 

Thought oplot would realy overwrite any exitisting Plot. Maybe there is some need for clarification at [http://newville.github.io/wxmplot/plotpanel.html](url) by changing overwriting to overlaying

**Comment by newville** [comment]
@kuch3n are you willing to make a PR on docs?

**Comment by kuch3n** [comment]
@newville  what do you mean by "make a PR on docs"?

**Comment by newville** [comment]
@kuch3n i meant are you willing to make a change to the document source files and make a pull request?  It's OK if not.....

**Comment by newville** [comment]
@kuch3n  I needed to push a new version 0.9.20 (for Phoenix support), and so made this change to the docs sources.  Will update the published doc soon.
