### ISSUE TITLE
"Zoom out" breaks mouse clicks

### ISSUE THREAD

**Issue by kuch3n** [newville/wxmplot#25]
Hi,
Reproducible with:
1. left click in plot 
2. click zoom out 
2.1 everything still clickable
3. left mouse down in view
4. mouse click breaks

Traceback:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/matplotlib/backends/backend_wx.py", line 1075, in _onLeftButtonDClick
    self.CaptureMouse()
  File "/usr/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 10638, in CaptureMouse
    return _core_.Window_CaptureMouse(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "!wxMouseCapture::IsInCaptureStack(this)" failed at ./src/common/wincmn.cpp(3271) in CaptureMouse(): Recapturing the mouse in the same window?
`
is this even a wxmplot bug?

PS: Didn't had the time for a PR on doc :(

**Comment by newville** [comment]
@kuch3n  No, it is not actually a wxmplot bug.   As you can see from the traceback, it comes from wxPython as it is called by matplotlib/backend_wx.py.

What versions of matplotlib and wx do you have? I've seen this bug with older versions, but don't see it with wxPython 3.0.3 and matplotlib 1.5.3.

**Comment by kuch3n** [comment]
Got wxPython 3.0.2 here and cant find version 3.0.3. Neither via pip nor on sourceforge.com. Only the wxPython Phoenix Package  has 3.0.3, which isn't in use here. 
matplotlib with version 1.5.3
Do i have to change to wxPython phoenix?

**Comment by newville** [comment]
@kuch3n  I'm not sure which versions of matplotib / wxPython/ OS  might be affected.   I do also see this on Linux with Python 2.7.11, wxPython 3.0.2 and matplotlib 1.4.3, but not on all other systems.

But, as mentioned earlier, I think this is really a bug from the wx backend of matplotlib.   It might be that wxmplot is especially good at exposing it, but I don't know for sure.

**Comment by newville** [comment]
@kuch3n Here's something to try:

In plotpanel.py `BuildPanel` there is code:

```python
        if sys.platform.lower().startswith('darw'):
            def swallow_mouse(*args):
                pass
            self.canvas.CaptureMouse = swallow_mouse
```

if you're on Linux (a guess from your path info), you could try changing the test there to
```python
        if os.name == 'posix':
            def swallow_mouse(*args):
                pass
            self.canvas.CaptureMouse = swallow_mouse
```

does that work for you?  Again, this should really be fixed in the matplotlib backend, but if that workaround works, at least we can submit an issue/pr based on that.

**Comment by kuch3n** [comment]
@newville i'll test it and write an issue with results of this on the mpl project :)

**Comment by newville** [comment]
@kuch3n I just pushed a change to master that does this in basepanel (so for both PlotPanel and ImagePanel) on all posix systems.  

Honestly, I don't know why the matplotlib backend does this capturing of the mouse at all.

**Comment by kuch3n** [comment]
Yep, this solves it, many thx :)

**Comment by kuch3n** [comment]
Issue moved to matplotlib
