### ISSUE TITLE
Is there a way to block zoom on a particular axis? 

### ISSUE THREAD

**Issue by kuch3n** [newville/wxmplot#27]
Can't see any hints on this in method `zoom_leftup`

**Comment by newville** [comment]
@kuch3n I'm not sure I understand, but I'll 

The wxmplot panels `PlotPanel` and `ImagePanel`  (both derived from `BasePanel`) can have a few "cursor modes", held in `self.cursor_mode`, with values of 'report', 'zoom', or 'lasso' currently supported.    Each of these modes is a key in the `self.cursor_modes` dict that hold the methods to be run on particular events.  

`BasePanel` uses the `add_cursor_mode()` to define these methods.  But you can overwrite these, for example, you could say 
```python
      self.cursor_modes['zoom']['leftup'] = MyZoomLeftUp
```

To completely ignore zooming and all other events on a particular panel, you can just set all those events to `None`.    See  https://github.com/newville/wxmplot/blob/master/lib/stackedplotframe.py#L140
and the next few lines.  This completely disables reporting and zooming on the lower panel (try examples/stackedplot.py).

**Comment by kuch3n** [comment]
@newville i want to block zoom on y-Axis and tooked the zoom_leftup method, get ymin and ymax for every axis (`ymin, ymax = ax.get_ylim()`)  and gave it to `tlims[ax]`. Thanks for the examples and hints :-)
