### ISSUE TITLE
Missing Function

### ISSUE THREAD

**Issue by crypt5** [newville/wxmplot#32]
I have a program that crashes when I use the Zoom feature. Zooming in or out does not work. I traced the problem back to the function set_viewlimits in basepanel. The problem is that the function, to my knowledge, doesn't exist. 

Is this a callback I am supposed to set in order for zoom to work?

**Comment by newville** [comment]
@crypt5  Does zoom with the wxmplot demos work for you?  These all work for me.

 Can you give a small, reproducible example that shows the problem?  Also, please give OS and versions of wxPython.

**Comment by crypt5** [comment]
Figured out it was a goof on my part. Thanks for the reply
