### ISSUE TITLE
UPDATE_LINE option

### ISSUE THREAD

**Issue by BorisKontorovich** [newville/wxmplot#35]
I was going through the demo.py example, there is an update_limits option in the update_line function (line 283) that does not seem to be found anywhere in the documentation.  I also don't see any difference with it set to either value.  Am I missing something?  Please, let me know.

**Comment by newville** [comment]
@BorisKontorovich Well, it might just be leftover cruft.  In `PlotPanel.updat_line` (see https://github.com/newville/wxmplot/blob/6a2455fc02061a898c40c6286cfb41a705384c7a/lib/plotpanel.py#L679, this option does force `set_viewlimits()` to be called.

I can fully believe that this is no longer necessary, but then again maybe it is important in some cases.  For sure, the dynamic updating ala `update_line` could be re-investigated.  Much of the wmplot code predates matplotlib v 1.0, so might be done better other ways.  Suggestions most welcome!

**Comment by newville** [comment]
@yanikou19  fixed doc to include `update_limits` option to `update_line()`.
