### ISSUE TITLE
Python36: missing UserDict in tests

### ISSUE THREAD

**Issue by kamischi** [newville/wxmplot#36]
With python36 `python%type_raw[python] setup.py test` fails with:

`    from UserDict import DictMixin`
`ModuleNotFoundError: No module named 'UserDict'`

Presumably, all python3 versions are affected.

**Comment by newville** [comment]
@kamischi uh, I guess I never used `setup.py test` ;).  `pytest` works for me, though not much of `wxmplot` is actually tested (not easy to test GUI code...)

To be clear, `wxmplot` definitely works with Python36 for me (I use that combination continuously), but we could probably remove `lib\ordereddict.py` completely and use `collections.OrderedDict` instead.

**Comment by kamischi** [comment]
Not a big problem. I am just writing up a fink package description for wxmplot and while doing so, i tried setup.py test and thought to report. There is actually surprising large number of python mods with failing tests, even with wider usage than wxmplot. 

Unfortunately, my python knowledge is still rather limited. So, I can't come up with a patch.

**Comment by newville** [comment]
I removed the older ordered dict code, so this is now fixed in master
