### ISSUE TITLE
Use of removed matplotlib APIs

### ISSUE THREAD

**Issue by christiansandberg** [newville/wxmplot#44]
The [register_cmap](https://matplotlib.org/stable/api/cm_api.html#matplotlib.cm.register_cmap) does not accept the lut keyword argument since 3.4.

See [documentation for 3.3](https://matplotlib.org/3.3.0/api/cm_api.html?highlight=register_cmap#matplotlib.cm.register_cmap) for the deprecation notice.

**Comment by newville** [comment]
@christiansandberg oh, thanks - I did not see that deprecation warning.  It seems like a pretty straightforward to fix, but a PR would be most welcome!
