### ISSUE TITLE
problem installing wxplot on MacOS 12.2.1

### ISSUE THREAD

**Issue by judoal** [newville/wxmplot#49]
got this error building wxpython after cloning the project and running pip install.  I had to  install wheel package separately to prevent use of legacy.  I also ran pip install wxpython which failed as well

 /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
        warnings.warn(
      running build_ext
      building 'wx.svg._nanosvg' extension
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -DNANOSVG_IMPLEMENTATION=1 -DNANOSVGRAST_IMPLEMENTATION=1 -DNANOSVG_ALL_COLOR_KEYWORDS=1 -Iext/nanosvg/src -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c wx/svg/_nanosvg.c -o build/wxsvg/temp.macosx-10.9-universal2-3.10/wx/svg/_nanosvg.o
      wx/svg/_nanosvg.c:5761:72: warning: array subscript is of type 'char' [-Wchar-subscripts]
          __pyx_t_2 = PyFloat_FromDouble((__pyx_v_self->_ptr->strokeDashArray[__pyx_v_i])); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 364, __pyx_L1_error)
                                                                             ^~~~~~~~~~
      wx/svg/_nanosvg.c:20946:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                  ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                        ^
      wx/svg/_nanosvg.c:20946:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
                  ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      wx/svg/_nanosvg.c:20951:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                  ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                        ^
      wx/svg/_nanosvg.c:20951:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
                  ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      wx/svg/_nanosvg.c:21035:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                  ret = _PyGen_Send((PyGenObject*)yf, NULL);
                        ^
      wx/svg/_nanosvg.c:21035:17: warning: incompatible integer to pointer conversion assigning to 'PyObject *' (aka 'struct _object *') from 'int' [-Wint-conversion]
                  ret = _PyGen_Send((PyGenObject*)yf, NULL);
                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      4 warnings and 3 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      Command '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 setup-wxsvg.py build_ext --inplace' failed with exit code 1.
      Finished command: build_others (0.906s)
      Finished command: build_py (0m17.292s)
      Finished command: build (0m26.553s)
      Command '"/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10" -u build.py build' failed with exit code 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wxPython

note: This is an issue with the package mentioned above, not pip.

**Comment by newville** [comment]
@judoal Like you say, that is a problem building / installing wxPython, not wxmplot itself.   Feel free to move this issue to wxPython - we're not going to solve it here! 

FWIW, I believe that wxPython wheels for Python 3.10 are not available on PyPI for any platforms.
For macOS, I find anaconda python and conda-forge to have good and up-to-date packages for wxPython.

**Comment by judoal** [comment]
Hi 

Thanks for the input.  I got anaconda python installed as was able to do the build.  However in the examples, I'm attempting to run the stripchart.py program using anaconda python. I'm getting a runtime error: "no module named 'floatcontrol'.  running pip to install it fails.  Since the example is on the wxmplot project, any ideas how to get it installed?

Thanks

Allen

**Comment by newville** [comment]
@judoal `floatcontrol.py` is in the examples folder along with `stripchart.py`: https://github.com/newville/wxmplot/blob/master/examples/floatcontrol.py

**Comment by judoal** [comment]
Got it. Thanks

Allen Gordon
