### ISSUE TITLE
problem with stripchart.py in examples directory

### ISSUE THREAD

**Issue by judoal** [newville/wxmplot#50]
The output is slightly different from running the original code with these changes, but the result is the same.  this tracback is:

Traceback (most recent call last):
  File "/Users/allengordon/Documents/workspace/pgsolar/wxmplot/examples/stripchart.py", line 110, in onTimer
    t2, y2 = next_data
TypeError: cannot unpack non-iterable function object
Traceback (most recent call last):
  File "/Users/allengordon/Documents/workspace/pgsolar/wxmplot/examples/stripchart.py", line 110, in onTimer
    t2, y2 = next_data
TypeError: cannot unpack non-iterable function object

running the somewhat modified code as is to plot one trace in real time works just fine.  However, I added some code to plot two traces and get  "TypeError:  'NoneType is not subscriptable'.  The code I changed is:

    def onTimer(self, event):   #5

        self.count += 1
        etime = time.time() - self.time0
        self.tmin = float(self.time_range.GetValue())
        t1, y1 = next_data()
        _**t2,y2 =next_data()**_    #new
        self.tlist.append(t1)
        _**self.tlist.append(t2)**_   #new
        self.ylist.append(y1)
        _**self.ylist.append(y2**)_    #new
        tdat = np.array(self.tlist) - t1
        mask = np.where(tdat > -abs(self.tmin))
        ydat = np.array(self.ylist)

The output is this:

<next_data>
1657906492.479019
0.31490781630084264
<next_data>
1657906493.479179
0.33375499766168376
Traceback (most recent call last):
  File "/Users/allengordon/Documents/workspace/pgsolar/schartdev/stripchart.py", line 145, in onTimer
    self.plotpanel.update_line(2, tdat, ydat, draw=True)
  File "/Users/allengordon/Documents/workspace/pgsolar/schartdev/wxmplot/plotpanel.py", line 713, in update_line
    x = self.conf.get_mpl_line(trace)
  File "/Users/allengordon/Documents/workspace/pgsolar/schartdev/wxmplot/config.py", line 738, in get_mpl_line
    return this[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by judoal** [comment]
I should have shown the line where the exception occurs (highlighted below):

       n = len(self.ylist)
        if n <= 2:
            self.plotpanel.plot(tdat, ydat)
        else:
            _**self.plotpanel.up.ylisdate_line(2, tdat, ydat, draw=True)**_
            self.write_message("update  %i points in %8.4f s" % (n,etime))

**Comment by newville** [comment]
@judoal I don't see any problem with the existing stripchart code and have no idea what you are doing. You did not post runnable code. Like, I might ask what the heck is   
```_**self.plotpanel.up.ylisdate_line(2, tdat, ydat, draw=True)**_```

supposed to convey, but, well, `plotpanel` does not have an `up` attribute, so that is clearly not ever going to be valid code.

You cannot expect me to debug code that you wrote and did not show.  If you are modifying code and it causes errors, that is sort of your responsibility.

I don't see any evidence of a problem with wxmplot.

**Comment by newville** [comment]
@judoal if I understand correctly, you are asking about changes in the stripchart code that you have made and don't work as you expect.

That has nothing to do with wxmplot.
