### ISSUE TITLE
Problem using plotlib in windows 11 Enterprise

### ISSUE THREAD

**Issue by ajsweene** [newville/wxmplot#52]
Receiving the following error in windows 11 Enterprise
Tried python versions: 3.8, 3.9, 3.10 with same result

  File "C:\Python38\lib\site-packages\wxmplot\basepanel.py", line 519, in gui_repaint
    and isinstance(self.canvas.figure._cachedRenderer, RendererWx)):
AttributeError: 'Figure' object has no attribute '_cachedRenderer'

Problem goes away when I comment out the following code block in basepanel.py

        if (wx.Platform == '__WXMSW__'
            and isinstance(self.canvas.figure._cachedRenderer, RendererWx)):
            bmp = bmp.ConvertToImage().ConvertToBitmap()

**Comment by newville** [comment]
@ajsweene Thanks for the report and sorry for the trouble.  This was also reported by a private email too, and I think this issue is solved in the `mpl_renderer` branch, and I will merge and push to PyPI soon.
